#!/usr/bin/env node
/**
 * Demonstrates: `expo export` binary-patches compiled Hermes bytecode to
 * rename a DOM component's html asset, and that in-place write corrupts any
 * string hermesc overlap-packed with the placeholder name.
 *
 * Two passes:
 *   1. export once to learn the DOM component reference -> placeholder
 *      filename hash H = md5(reference)  (deterministic per checkout)
 *   2. plant "victim" string literals ENDING in prefixes of H (hermesc's
 *      packer fuses shared suffix/prefix bytes), export again, and check
 *      whether the victims survive in the bytecode.
 *
 * Expected (bug present): victims sharing enough bytes with H are truncated —
 * their tails overwritten by the renamed html's new content-hash.
 */
const { execSync, spawnSync } = require('child_process')
const crypto = require('crypto')
const fs = require('fs')
const path = require('path')

const run = (cmd, env = {}) =>
  spawnSync('npx', cmd.split(' '), {
    cwd: __dirname,
    env: { ...process.env, CI: '1', ...env },
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024,
  })

console.log('── pass 1: discover the DOM component placeholder hash ──')
const p1 = run('expo export --platform ios --output-dir dist1', { DEBUG: 'expo:*' })
const debugOut = p1.stderr + p1.stdout
const ref = debugOut.match(/Bundle DOM Component[.:'\s]*([^\n']+)/)?.[1]?.trim()
if (!ref) {
  console.error('could not find "Bundle DOM Component:" in DEBUG output; tail:')
  console.error(debugOut.slice(-2000))
  process.exit(2)
}
const H = crypto.createHash('md5').update(ref).digest('hex')
console.log(`reference       : ${ref}`)
console.log(`placeholder     : ${H}.html`)

console.log('── pass 2: plant victims that end in prefixes of the placeholder ──')
const lengths = [4, 6, 8, 12, 16]
const victims = Object.fromEntries(
  lengths.map((n) => [`overlap${n}`, `victim-${String(n).padStart(2, '0')}-${'x'.repeat(20 - n)}-${H.slice(0, n)}`])
)
victims.control = `victim-cc-${'x'.repeat(12)}-deadbeef`
fs.writeFileSync(
  path.join(__dirname, 'victims.ts'),
  `// generated by repro.js\nexport const VICTIMS: Record<string, string> = ${JSON.stringify(victims, null, 2)}\n`
)
const p2 = run('expo export --platform ios --output-dir dist2')
if (p2.status !== 0) {
  console.error('export failed:', (p2.stderr || '').slice(-1500))
  process.exit(2)
}

const iosDir = path.join(__dirname, 'dist2/_expo/static/js/ios')
const hbcFile = fs.readdirSync(iosDir).find((f) => f.endsWith('.hbc'))
const hbc = fs.readFileSync(path.join(iosDir, hbcFile))
console.log(`bytecode        : ${hbcFile} (${hbc.length} bytes)`)

let corrupted = 0
for (const [name, value] of Object.entries(victims)) {
  const intact = hbc.includes(Buffer.from(value, 'utf8'))
  if (!intact) {
    corrupted++
    // show what the bytes actually say now
    const head = Buffer.from(value.slice(0, 10), 'utf8')
    const at = hbc.indexOf(head)
    const actual = at >= 0 ? hbc.slice(at, at + value.length).toString('latin1') : '(head not found)'
    console.log(`  ${name.padEnd(9)} CORRUPTED  expected …${value.slice(-14)}  got …${actual.slice(-14)}`)
  } else {
    console.log(`  ${name.padEnd(9)} intact`)
  }
}

console.log('')
if (corrupted > 0) {
  console.log(`FAIL: ${corrupted} string literal(s) corrupted in the compiled bytecode by the DOM html rename.`)
  process.exit(1)
} else {
  console.log('PASS: all planted strings intact (bug not reproduced on this run).')
}
