// generated by repro.js
export const VICTIMS: Record<string, string> = {
  "overlap4": "victim-04-xxxxxxxxxxxxxxxx-d950",
  "overlap6": "victim-06-xxxxxxxxxxxxxx-d95002",
  "overlap8": "victim-08-xxxxxxxxxxxx-d950027d",
  "overlap12": "victim-12-xxxxxxxx-d950027da9f0",
  "overlap16": "victim-16-xxxx-d950027da9f038ca",
  "control": "victim-cc-xxxxxxxxxxxx-deadbeef"
}
